print("Googl",end="Form")
Name= input("enter your name:")
Father_name= input("enter your Father name:")
Date_of_birth= input("enter your Date of birth:")
Gender= input("enter your Gender:")
age= int(input("enter your age:"))
email= input("enter your email:")
phone_num= int(input("enter your phone_num:"))
Education= input("enter your Education:")
Matric_marks= int(input("enter your name:"))
Intermediate_marks= int(input("enter your Intermedite marks: "))
bsc_gpa= int(input("enter your bsc marks:"))
Experience=int(input("enter youre experience"))

print("enter your  name",Name)
print("enter your Father name",Father_name)
print("enter your  Date of birth",Date_of_birth)
print("enter your  Gender",Gender)
print("enter your  age",age)
print("enter your email",email)
print("enter your phone num",phone_num)
print("enter your Feducation",Education)
print("enter your  Matric marks",Matric_marks)
print("enter your  Intermediate marks",Intermediate_marks)
print("enter your  bsc gpa",bsc_gpa)
print("enter your Experience",Experience)