print("      *                                 *"      ,"\n")
print("   *    *                          *         *"   ,"\n")
print("  *       *                    *                 *","\n")
print(" ***** *****                ******             ******","\n")
print("     * *                         *             *","\n")
print("     * *                         *             *","\n")
print("     * *                         *             *","\n")
print("     ***                         ***************")
print("   NOBITA                         DORAMON")