
date=int(input("enter your date e.g 03:"))
month=(int(input("enter your month e.g 04:")))
year=int(input("enter your year:"))
d=str(date)
m=str(month)
y=str(year)
element=(d,m,y)
var='-'.join(element)
print(var)
